---
# [pt_BR] Configurações de intervalos de tempo
  time_intervals:
    
    # [pt_BR] Intervalo de tempo para verificar se há heróis disponíveis para trabalhar
    # Valor padrão (em minutos): 10
    send_heroes_for_work: 10

    # [pt_BR] Intervalo de tempo para atualizar a posição dos heróis no mapa
    # Valor padrão (em minutos): 5
    refresh_heroes_positions: 5
    
    # [pt_BR] Intervalo de tempo para verificar por novos mapas
    # Valor padrão (em segundos): 2
    check_for_new_map_button: 1

    # [pt_BR] Intervalo de tempo para verificar se precisa resolver o captcha.
    # Valor padrão (em minutos): 2
    check_for_captcha: 2

    # [pt_BR] Intervalo de tempo para verificar se existe solicitação de login
    # Valor padrão (em minutos): 1
    check_for_login: 1

    # [pt_BR] Intervalo de tempo entre movimentos
    # Valor padrão (em segundos): 1
    interval_between_moviments: 1


  # [pt_BR] O quão confiante o bot precisa estar para clicar nos botões (valores entre 0 e 1. 0 é o valor mínimo, 1 é o valor máximo)
  threshold:
    # [pt_BR]
    # Valor padrão: 0.7
    default: 0.7

    # [pt_BR]
    # Valor padrão: 0.8
    commom: 0.8

    # [pt_BR]
    # Valor padrão: 0.8
    select_wallet_buttons: 0.8

    # [pt_BR]
    # Valor padrão: 0.9
    go_to_work_btn: 0.9

    # [pt_BR]
    # Valor padrão: 0.9
    green_bar: 0.9

  home:
    enable: False
    # If bot is sending the wrong hero home, make this number bigger.
    # if bot is not sending any hero home make this number smaller.
    hero_threshold: 0.8
    home_button_threshold: 0.9

  # [pt_BR]
  # Valor padrão: 60
  scroll_size: 60

  # [pt_BR]
  # Valor padrão: 3
  scroll_attemps: 1

  # [pt_BR]
  # Valor padrão: true
  use_click_and_drag_instead_of_scroll: true

  # [pt_BR]
  # Valor padrão: 200
  click_and_drag_amount: 200

  # [pt_BR]
  # Valor padrão: green
  # Opções disponíveis:
  # all   = seleciona todos os heróis (independente da barra de stamina)
  # green = seleciona os heróis com a barra de stamina verde (metade ou cheia)
  # full  = seleciona somente os heróis com a barra de stamina cheia
  select_heroes_mode: "full"

  # [pt_BR] Opção para salvar os logs em arquivo (logs.txt)
  # Valor padrão : False
  # Opções disponíveis: False ou True
  save_log_to_file: True
